on: push

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Render PlantUML to Wiki
        uses: frederikheld/render-plantuml-to-wiki-action@v1.0.1
        with:
          WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}
          INPUT_DIR: .
          OUTPUT_DIR: images/
