- name: Render PlantUML to Wiki
  uses: frederikheld/render-plantuml-to-wiki-action@v1.0.1
  with:
    # Secure token to access wiki repo
    WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}
    # Directory in repo to read PlantUML source files from
    INPUT_DIR: 'uml/'
    # Directory in wiki to write rendered diagrams to
    OUTPUT_DIR: 'images/'
